# Site settings
title: msimonin@github.io
email: matthieu.simonin@inria.fr
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://msimonin.github.io" # the base hostname & protocol for your site
twitter_username: simoninmatthieu
github_username:  msimonin

# Build settings
markdown: kramdown
